server:
  address: 0.0.0.0
  port: 9443
  ssl:
    enabled: true
    key-store: classpath:xn--tfrza1844az9b.cn.jks
    key-store-password: 06o0wz63q09h75
    key-store-type: JKS
  servlet:
    context-path: /server
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:my/suveng/server/modules/user/mapper/*/*.xml
  type-aliases-package: my.suveng.server.modules.*.entity
spring:
  datasource:
    druid:
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 最大连接池数量
      max-active: 30
      # 最小连接池数量
      min-idle: 5
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 300000
      # 用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 1 FROM DUAL
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: true
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-pool-prepared-statement-per-connection-size: 50
      # 合并多个DruidDataSource的监控数据
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      use-global-data-source-stat: true
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 500
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    charset: utf-8
    allow-request-override: false
    allow-session-override: false
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    #    prefix:                                               #在构建URL时添加前缀
    request-context-attribute: request                    #在 ftl 中使用 request.contextPath
    settings: {"date_format":"yyyy-MM-dd","datetime_format":"yyyy-MM-dd HH:mm:ss"}
    #    view-names:
    suffix: .ftl
  clickhouse:
    url: jdbc:clickhouse://192.168.174.185:8123
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    username:
    password:
  mysql:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.230.95.206:3306/system?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
