spring:
  profiles:
    active: dev
server:
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-alias: tomcat
    key-store-password: 123456
  servlet:
    context-path: /springboot




